### 게시판 조회
GET http://localhost:8080/api/v1/board/1

### 게시판 페이지 조회
GET http://localhost:8080/api/v1/board/1?page=5

### 게시글 조회
GET http://localhost:8080/api/v1/article/1

### 댓글 조회
GET http://localhost:8080/api/v1/comment/1

### 게시글의 댓글 조회
GET http://localhost:8080/api/v1/article/1/comments

### 관리자 로그인
POST http://localhost:8080/api/login?username=admin&password=admin
Content-Type: application/x-www-form-urlencoded

### 사용자 로그인
POST http://localhost:8080/api/login?username=user&password=user
Content-Type: application/x-www-form-urlencoded

### auth test
GET http://localhost:8080/api/v1/test/auth
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY2MTY5MDMwMH0.JbkvAyrZPEO8AZkXh8rslV56wBrECGGhVgxXWKcENaw

### 게시글 작성
POST http://localhost:8080/api/v1/board/1/write
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NjE2OTA0OTB9.TdJtOH3j5Xe9paVZVrrX3-LWM1YAxi2AfvLOlAuQb7g
Content-Type: application/json

{
  "title": "Test Title",
  "content": "Contents"
}

### 게시글 조회
GET http://localhost:8080/api/v1/article/3

### GET ENV
GET http://localhost:8080/api/v1/test/env

### 파일 업로드
POST http://localhost:8080/api/v1/media
Content-Type: multipart/form-data; boundary=PLATABOARDTEST
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY2MTY5MDUyMn0.Oa5EboKtIwS1iF6MpVL2UmPXrXzEQeFzRECUaoLubg4

--PLATABOARDTEST
Content-Disposition: form-data; name="expireDate"

2022-08-28T01:26:46.653101
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="imageuploadtest.jpg"
Content-Type: image/jpeg

< ./IMG_5181.JPG
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="test2.xml"
Content-Type: application/xml

< ./checkstyle-google-4depth.xml
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="test3.xml"
Content-Type: application/xml

< ./checkstyle-google-4depth.xml
--PLATABOARDTEST--

### media get
GET http://localhost:8080/media/attach/1

### media get
GET http://localhost:8080/media/image/2022/08/28/ec7b0c5d-88fb-461e-b284-d52a0dbfc793.jpg

### media delete
DELETE http://localhost:8080/api/v1/media/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NjE2OTA0OTB9.TdJtOH3j5Xe9paVZVrrX3-LWM1YAxi2AfvLOlAuQb7g

### media delete2
DELETE http://localhost:8080/api/v1/media/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY2MTY5MDMwMH0.JbkvAyrZPEO8AZkXh8rslV56wBrECGGhVgxXWKcENaw


### medie real delete (관리자 권한)
DELETE http://localhost:8080/api/v1/media/fileDeleteFromStorage/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY2MTY5MDUyMn0.Oa5EboKtIwS1iF6MpVL2UmPXrXzEQeFzRECUaoLubg4
