### 게시판 조회
GET http://localhost:8080/api/v1/board/1

### 게시판 페이지 조회
GET http://localhost:8080/api/v1/board/1?page=5

### 게시글 조회
GET http://localhost:8080/api/v1/article/4

### 댓글 조회
GET http://localhost:8080/api/v1/comment/1

### 게시글의 댓글 조회
GET http://localhost:8080/api/v1/article/1/comments

### 관리자 로그인
POST http://localhost:8080/api/login?username=admin&password=admin
Content-Type: application/x-www-form-urlencoded

### 사용자 로그인
POST http://localhost:8080/api/login?username=user&password=user123
Content-Type: application/x-www-form-urlencoded

### auth test
GET http://localhost:8080/api/v1/test/auth
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM

### 게시글 작성
POST http://localhost:8080/api/v1/board/1/write
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM
Content-Type: application/json

{
  "title": "Test Title",
  "content": "Contents"
}

### 게시글 조회
GET http://localhost:8080/api/v1/article/3

### 게시글 추천
POST http://localhost:8080/api/v1/article/4/recommend
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM

### Executing an update/delete query; nested exception is javax.persistence.TransactionRequiredException: Executing an update/delete query

### 게시글 수정
POST http://localhost:8080/api/v1/article/3/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM
Content-Type: application/json

{
  "title": "3333 Test Title",
  "content": "3333 Contents"
}


### 게시글 삭제
DELETE http://localhost:8080/api/v1/article/4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM

### 코멘트 조회
GET http://localhost:8080/api/v1/article/3/comments

### 코멘트 작성
POST http://localhost:8080/api/v1/article/3/comment
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzM4ODE2NzksInVzZXJJZCI6IjIifQ.UwdQdkPINuR7f4hubw4zrSq_cCcpkgmycd5A1JAngdM
Content-Type: application/json

{
  "content": "Test Comment"
}

### 코멘트 수정
POST http://localhost:8080/api/v1/comment/16/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-WfsF
Content-Type: application/json

{
  "content": "34444333Test Comment"
}

### 코멘트 삭제
DELETE http://localhost:8080/api/v1/comment/16
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-Wfs


### GET ENV
GET http://localhost:8080/api/v1/test/env

### 파일 업로드
POST http://localhost:8080/api/v1/media
Content-Type: multipart/form-data; boundary=PLATABOARDTEST
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-Wfs

--PLATABOARDTEST
Content-Disposition: form-data; name="expireDate"

2022-08-28T01:26:46.653101
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="imageuploadtest.jpg"
Content-Type: image/jpeg

< ./IMG_5181.JPG
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="test2.xml"
Content-Type: application/xml

< ./checkstyle-google-4depth.xml
--PLATABOARDTEST
Content-Disposition: form-data; name="files"; filename="test3.xml"
Content-Type: application/xml

< ./checkstyle-google-4depth.xml
--PLATABOARDTEST--

### media get
GET http://localhost:8080/media/attach/1

### media get
GET http://localhost:8080/media/image/2022/08/28/ec7b0c5d-88fb-461e-b284-d52a0dbfc793.jpg

### media delete
DELETE http://localhost:8080/api/v1/media/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-Wfs

### media delete2
DELETE http://localhost:8080/api/v1/media/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-Wfs

### medie real delete (관리자 권한)
DELETE http://localhost:8080/api/v1/media/fileDeleteFromStorage/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2NzIxNDEwMDAsInVzZXJJZCI6IjIifQ.AHhCGpq8SkhgFigpIWrY5a4Gl6BAxrz58sNHHfo-Wfs
