package org.platanus.webboard.domain.utils;

public class QueryConst {
    public static final String BOARD_DELETE = "delete from BOARDS where ID = ?";
    public static final String BOARD_UPDATE = "update BOARDS set NAME = ?, DESCRIPTION = ?  where ID = ?";
    public static final String BOARD_FIND_ALL = "select * from BOARDS";
    public static final String BOARD_FIND_BY_ID = "select * from BOARDS where ID = ?";
    public static final String BOARD_FIND_BY_NAME = "select * from BOARDS where NAME = ?";
    public static final String BOARD_ALL_DELETE = "delete from BOARDS";
    public static final String ARTICLE_DELETE = "delete from ARTICLES where ID = ?";
    public static final String ARTICLE_UPDATE = "update ARTICLES set TITLE = ?, CONTENT = ?, MODIFIED_DATE = ? where ID = ?";
    public static final String ARTICLE_UPDATE_VIEW_COUNT = "update ARTICLES set VIEW_COUNT = VIEW_COUNT + 1 where ID = ?";
    public static final String ARTICLE_UPDATE_RECOMMEND = "update ARTICLES set RECOMMEND = RECOMMEND + 1 where ID =?";
    public static final String ARTICLE_UPDATE_DELETE_FLAG = "update ARTICLES set DELETED = ? where ID = ?";
    public static final String ARTICLE_FIND_BY_ID = "select * from ARTICLES where ID = ?";
    public static final String ARTICLE_FIND_BY_BOARD_ID = "select * from ARTICLES where BOARD_ID = ? order by ID desc";
    public static final String ARTICLE_FIND_BY_BOARD_ID_PAGE = "select * from ARTICLES where BOARD_ID = ? order by ID desc limit ? offset ?";
    public static final String ARTICLE_FIND_ALL = "select * from ARTICLES";
    public static final String ARTICLE_FIND_BY_AUTHOR_ID = "select * from ARTICLES where AUTHOR_ID = ?";
    public static final String ARTICLE_FIND_BY_TITLE = "select * from ARTICLES where TITLE like ?";
    public static final String ARTICLE_FIND_BY_CONTENT = "select * from ARTICLES where CONTENT like ?";
    public static final String ARTICLE_FIND_BY_TITLE_AND_CONTENT = "select * from ARTICLES where TITLE like ? or CONTENT like ?";
    public static final String ARTICLE_ALL_DELETE = "delete from ARTICLES";
    public static final String ARTICLE_COUNT = "select count(*) from ARTICLES where board_id =?";
    public static final String ARTICLE_RECOMMEND_FIND_BY_ARTICLE_ID_AND_USER_ID = "select * from ARTICLES_RECOMMEND where ARTICLE_ID = ? and USER_ID = ?";
    public static final String ARTICLE_RECOMMEND_FIND_BY_ARTICLE_ID = "select * from ARTICLES_RECOMMEND where ARTICLE_ID = ?";
    public static final String ARTICLE_RECOMMEND_FIND_BY_USER_ID = "select * from ARTICLES_RECOMMEND where USER_ID = ?";
    public static final String ARTICLE_RECOMMEND_COUNT_BY_ARTICLE_ID = "select count(*) from ARTICLES as A inner join ARTICLES_RECOMMEND as AR on A.ID = AR.ARTICLE_ID where AR.ARTICLE_ID = ?";
    public static final String ARTICLE_RECOMMEND_COUNT_BY_USER_ID = "select count(*) from ARTICLES as A inner join ARTICLES_RECOMMEND as AR on AR.ARTICLE_ID = A.ID WHERE AR.USER_ID = ?";
    public static final String COMMENT_DELETE = "delete from COMMENTS where ID = ?";
    public static final String COMMENT_UPDATE = "update COMMENTS set CONTENT = ?, MODIFIED_DATE=? where ID = ?";
    public static final String COMMENT_UPDATE_DELETE_FLAG = "update COMMENTS set DELETED = ? where ID = ?";
    public static final String COMMENT_FIND_BY_ID = "select * from COMMENTS where ID = ?";
    public static final String COMMENT_FIND_BY_ARTICLE_ID = "select * from COMMENTS where ARTICLE_ID = ?";
    public static final String COMMENT_FIND_COUNT_BY_ARTICLE_ID = "select count(*) from COMMENTS where ARTICLE_ID = ? and DELETED = 0";
    public static final String COMMENT_FIND_BY_CONTENT = "select * from COMMENTS where CONTENT like ?";
    public static final String COMMENT_FIND_ALL = "select * from COMMENTS";
    public static final String USER_DELETE = "delete from USERS where ID = ?";
    public static final String USER_UPDATE = "update users set USERNAME =?, PASSWORD = ?, NICKNAME = ?, EMAIL = ? where ID = ?";
    public static final String USER_UPDATE_DELETE_FLAG = "update USERS set DELETED = ? where ID = ?";
    public static final String USER_FIND_BY_ID = "select * from USERS where ID = ?";
    public static final String USER_FIND_BY_USERNAME = "select * from USERS where USERNAME = ?";
    public static final String USER_FIND_BY_EMAIL = "select * from USERS where EMAIL = ?";
    public static final String USER_FIND_BY_NICKNAME = "select * from USERS where NICKNAME = ?";
    public static final String USER_FIND_BY_ROLE = "select * from USERS where ROLE = ?";
    public static final String USER_FIND_ALL = "select * from USERS";
    public static final String USER_ALL_DELETE = "delete from USERS";
}
